# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FOLIO Developer
description: >
  FOLIO is a new open source, cloud hostable, app-store based
  library platform, designed to facilitate collaboration between
  disparate development teams.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dev.folio.org" # the base hostname & protocol for your site
foliourl: https://www.folio.org/
wikiurl: https://wiki.folio.org/
discussurl: https://discuss.folio.org
issuesurl: https://issues.folio.org
roadmapurl: https://wiki.folio.org/display/PC/FOLIO+Roadmap
twitterurl: https://twitter.com/folio_lsp
blogurl: https://wiki.folio.org/pages/viewrecentblogposts.action?key=PC
google_analytics: UA-79833310-3

# Build settings
markdown: kramdown
theme: minima

exclude: [Gemfile, Gemfile.lock, CONTRIBUTING.md, README.md, vendor, work]

collections:
  posts:
    permalink: /news/:year/:month/:day/:title/
