# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FOLIO Developer
description: >
  FOLIO is a new open source, cloud hostable, app-store based
  library platform, designed to facilitate collaboration between
  disparate development teams.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dev.folio.org" # the base hostname & protocol for your site
google_analytics: UA-79833310-3
github_username: folio-org
twitter_username: folio_lsp

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-gist

exclude: [bin, Gemfile, Gemfile.lock, CONTRIBUTING.md, README.md, tmp, vendor, work]

defaults:
- scope:
    path: _reference
    type: reference
  values:
    layout: reference
    sectionid: reference
    
collections:
  posts:
    permalink: /news/:year/:month/:day/:title/
  reference:
    permalink: /reference/:path/
    output: true 